language: python
python:
  - "3.8.1"
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py sources_initialise
  - python manage.py politicians_initialise
  - python manage.py test
