language: python
python:
  - "3.8.1"
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py makemigrations agencies hansards politicians posts visualizations userprofile
  - python manage.py migrate
  - python manage.py aggregator --init
  - python manage.py aggregator --rss
  - python manage.py aggregator --scrap
  - python manage.py initialise --state sarawak
  - python manage.py initialise --state federal
  - python manage.py tweets --test simkuihian
  - python manage.py wikipedia --all
  - python manage.py test
